### PR TITLE
Allow passthrough of arguments from CLI to test binary

### PR DESCRIPTION
**Pull request by benbrittain**
Ex: buck2 test //path/to/test:target -- -- --gtest_filter=ARGS

Addresses #271

### CODE REVIEW

**Comment by benbrittain** [comment]
It would be nice if I could drop the double `-- --` down to a single `--`, but that reaches into some core CLI stuff which I don't have full insight into the requirements of.

**Comment by benbrittain** [comment]
@davidbarsky says he thinks the `-- --` is the same behavior as internal, so I'm not as worried about it anymore.

**Comment by stepancheg** [comment]
For now there are two possible workarounds:

```
buck2 run //test:binary
buck2 test //test:binary -- --env GTEST_FILTER=xxx
```

Add passthrough arguments to test subcommand may defeat the purpose of `test` command (which should be aware of test framework, and translate own filter arguments into test framework filter arguments), and may complicate proper implementation of open source test runner. Maybe we should add passthrough argument anyway, I don't know.

**Comment by benbrittain** [comment]
Is the idea that the open source test runner should eventually be aware of stuff like `gtest` and tools will take a `--filter=<regex>` and it'll be translated to the right framework automatically?

also, I don't think Rust has a `--env` equivalent for it's testing framework unfortunately (but the `run` workaround does work).

**Comment by stepancheg** [comment]
> Is the idea that the open source test runner should eventually be aware of stuff like gtest and buck2 test will take a --filter=<regex> and it'll be translated to the right framework automatically?

This is how internal test runner works, and source version of test runner should just use the same logic I think.

The idea is this. Suppose you have a CI. CI says: this test failed, this is repro command. CI should not know what was the test framework. CI should say: repro command is `buck2 test //foo:bar --filter baz`.

For that reason, test rules pass `test_type` string to `ExternalRunnerTestInfo` provider, for example, here:

https://github.com/facebook/buck2/blob/76a5520b048ae2fc09a980dde4cf8d6885441132/prelude/cxx/cxx.bzl#L588-L589

Test runner uses this string to convert own filter args to test framework specific args.

**Comment by ndmitchell** [comment]
The problem with this is that we can't add any new flags to the command ever, as we can't tell if they would have been used previously. While I agree with @nga that long term we do want more careful stuff, we shouldn't let perfect by the enemy of doing something.

What if we had:

```
Ex: buck2 test //path/to/test:target -- --extra-test-arg=--gtest_filter=ARGS
```

Now only the `extra-test-arg` need parsing and passing onwards, and while we might discourage it internally, it's not too problematic. Thoughts?

**Comment by benbrittain** [comment]
Yup, that seems really reasonable. Now that I understand the philosophy/goal state of the test CLI interface it seems like the right option.

For example, We have a couple of in-house ancient test runners that haven't been upgraded to gtest yet. I'd never want to add support for them, but this lets us use them with buck2 as well.


I'd suggest it being `--extra-arg` or `--raw-arg` or even just `--arg`. That keeps consistency between the naming of `env` and `arg`.

**Comment by ndmitchell** [comment]
If we already have `--env` then `--arg` does seem like the logical thing to add.

**Comment by benbrittain** [comment]
Pulled this up again, and I'm not sure the original premise is accurate.

```
Ex: buck2 test //path/to/test:target -- -- --gtest_filter=ARGS
or 
buck2 test //path/to/test:target -- -- rust_test_name --nocapture
```

shouldn't  prevent adding new arguments, anything that was passed through directly is behind the `--`.

**Comment by benbrittain** [comment]
Super simple tweak to make it `--arg=ARG`  instead :+1:

**Comment by cjhopman** [comment]
Is --env implemented by buck itself or by the test runner? I think it would be reasonable for us to say that part of the test runner spec is that there are some command line args that it is expected to handle in specific ways. We may want to consider early on if there should be more such args that we want to reserve in that way.

**Comment by benbrittain** [comment]
It's implemented by the open source test runner.

https://github.com/facebook/buck2/blob/main/app/buck2_test_runner/src/config.rs#L20

**Comment by benbrittain** [comment]
Is there anything blocking this landing? Every time I rebuild buck I need to cherry-pick this commit, which isn't great. I understand there are plans to make the OSS test runner significantly better, but it currently is not particularly usable. (e.g, needing to pass things like `--nocapture` through)

**Comment by ndmitchell** [comment]
Thanks, and sorry for the delay in getting this sorted. There was a lot of internal debate, including with people who were on holiday, which slowed it down. The conclusion is that we don't really like this, but at the moment if you don't have it you are definitely harmed, so we want to merge this now, but when we rework TestInfo (in a way that will give many more features to open source and make Tpx do more Meta-specific things rather than general execution) we'll probably remove it. But until then, this is a good useful feature to have.

We also think that renaming it to `--test-arg` is probably a better choice, since that is more explicit and [matches Bazel](https://bazel.build/docs/user-manual#test-arg). I'll make that change internally.

**Comment by benbrittain** [comment]
I understand the concern! I look forward to the day where we don't need this :)

**Pull request closed without merging**
