### PR TITLE
feat(remote_execution): attach RequestMetadata for non-fbcode builds

### PR DESCRIPTION
**Pull request by thoughtpolice**
Summary: When doing requests to a RBE service, it's useful to attach the 'RequestMetadata' type defined by Bazel onto gRPC requests, using a specific header.

This is actually already done, more or less, but only for the internal fbcode build service which uses a different and simpler Metadata structure, and a different header. Therefore attaching a new header isn't so complicated.

This also ensures that non-fbcode builds of Buck2 don't bother attaching fbcode Metadata, since it's not useful and can only be tested internally there, anyway. And likewise, we don't attach OSS Bazel RequestMetadata to fbcode_build configurations, either.

Test Plan: NIH.

Change-Id: Irrsqpmptqmzzoukzuzrqmkxsoqtxvuvx

### CODE REVIEW

**Comment by thoughtpolice** [comment]
This will eventually fix #256, but it isn't ready yet. Just wanted to file it to get it out of the way.

**Comment by krallin** [comment]
Could we preferably expose this via a config option rather than a build flag? We do use our internal RE in order to test the OSS build, and that doesn't build with fbcode_build, so this would break that testing.

**Comment by thoughtpolice** [comment]
Exactly why I drafted this instead of just submitting! I figured there would be some catch I didn't understand. I can rework this a little later.

**Comment by JakobDegen** [comment]
#502 has landed which incorporates all of this and then some, so I'm gonna close this. Feel free to reopen if you disagree

**Pull request closed without merging**
