### PR TITLE
Add remote execution example for NativeLink

### PR DESCRIPTION
**Pull request by aleksdmladenovic**

### CODE REVIEW

**Comment by JakobDegen** [comment]
Very cool, thank you!

**Comment by aleksdmladenovic** [comment]
Could you review this stuff and merge?
Thanks. @JakobDegen .

**Comment by MarcusSorealheis** [comment]
Super cool. Wow.

**Comment by aleksdmladenovic** [comment]
Thanks. @JakobDegen . I will be waiting for feedback.

**Pull request closed without merging**
