### PR TITLE
Bump rust toolchain to nightly 2023-06-23

### PR DESCRIPTION
**Pull request by benbrittain**
* Fixes ICE in the Github CI
* NodeKey enum size decrease

### CODE REVIEW

**Comment by thoughtpolice** [comment]
Is there any insight into exactly what is triggering this ICE? I have a nightly build of buck2 on Linux that gets updated every day [in this repository](https://github.com/thoughtpolice/buck2-nix/), but I haven't seen any ICEs at all in my builds, despite the fact this seems completely reproducible and happens across multiple OSs/architectures.

**Comment by benbrittain** [comment]
I honestly have no idea. I tried permuting a few things before attempting a toolchain upgrade which seems to have removed the ICE entirely. (looks like I should fix the other builders though too)

**Comment by stepancheg** [comment]
Bumping is not that easy, because we synchronize the version with the version used in internal non-cargo builds (in particular, size changes will break internal builds).

**Comment by dtolnay** [comment]
We have an upgrade to 1.71.0-beta.3 in progress, because of the ICEs with 1.70.0-stable. That will fix the GitHub CI &mdash; hopefully by early next week. @diliop

**Comment by dtolnay** [comment]
23efaf53ecf6737cb215686e244ff99874f647be

**Comment by dtolnay** [comment]
CI builds are working again:

Screenshot from 2023-06-28 13-28-47

**Pull request closed without merging**
